routing_mode = "REGIONAL"
name = "vpc-useast-03"
zone = "us-east4-a"
region = "us-east4"
project = "peaceful-branch-279707"
auto_create_subnetworks = "false"
description = "This VPC will be used for Business & Application instances in Production Network"
