peernetwork = "projects/peaceful-branch-279707/global/networks/vpc-useast-01"
zone = "us-east4-a"
autocreateroutes = "false"
region = "us-east4"
name = "peering-useast-02"
project = "peaceful-branch-279707"
network = "projects/peaceful-branch-279707/global/networks/vpc-useast-03"
